"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  AlertCircle,
  Check,
  ChevronLeft,
  Copy,
  Key,
  LogOut,
  Plus,
  RefreshCw,
  Trash2,
  UserPlus,
  X,
} from "lucide-react";
import GlobalHeader from "@/components/ui/GlobalHeader";
import GlobalFooter from "@/components/ui/GlobalFooter";
import { api } from "@/lib/api";
import { fetchMe, signOut, type ScopeResponse } from "@/lib/auth";

type UserRow = Awaited<ReturnType<typeof api.adminListUsers>>[number];
type TenantRow = Awaited<ReturnType<typeof api.adminListTenants>>[number];

type Reveal =
  | { kind: "create"; user: UserRow; password: string; autoGenerated: boolean }
  | { kind: "reset"; userId: string; password: string; autoGenerated: boolean };

const ROLES = ["owner", "admin", "member"] as const;
const STATUSES = ["invited", "active", "suspended", "offboarded"] as const;

export default function AdminUsersPage() {
  const router = useRouter();
  const [scope, setScope] = useState<ScopeResponse | null>(null);
  const [tenants, setTenants] = useState<TenantRow[] | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [users, setUsers] = useState<UserRow[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [reveal, setReveal] = useState<Reveal | null>(null);

  useEffect(() => {
    void (async () => setScope(await fetchMe()))();
    void (async () => {
      try {
        const list = await api.adminListTenants();
        setTenants(list);
        if (list.length > 0) setSelected(list[0].id);
      } catch (e) {
        setError((e as Error).message);
      }
    })();
  }, []);

  useEffect(() => {
    if (!selected) return;
    void (async () => {
      setBusy("load");
      setError(null);
      try {
        setUsers(await api.adminListUsers(selected));
      } catch (e) {
        setError((e as Error).message);
      } finally {
        setBusy(null);
      }
    })();
  }, [selected]);

  const refresh = async () => {
    if (!selected) return;
    setUsers(await api.adminListUsers(selected));
  };

  const onChangeRole = async (user: UserRow, role: typeof ROLES[number]) => {
    if (role === user.role) return;
    setBusy(user.id);
    try {
      await api.adminUpdateUser(user.id, { role });
      await refresh();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  };

  const onChangeStatus = async (user: UserRow, status: typeof STATUSES[number]) => {
    if (status === user.status) return;
    setBusy(user.id);
    try {
      await api.adminUpdateUser(user.id, { status });
      await refresh();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  };

  const onResetPassword = async (user: UserRow) => {
    if (!confirm(`Reset password for ${user.email}?\nAll their active sessions will be revoked.`))
      return;
    setBusy(user.id);
    try {
      const res = await api.adminResetUserPassword(user.id);
      setReveal({
        kind: "reset",
        userId: res.user_id,
        password: res.new_password,
        autoGenerated: res.auto_generated,
      });
      await refresh();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  };

  const onOffboard = async (user: UserRow) => {
    if (!confirm(`Offboard ${user.email}?\nThe user is preserved for audit purposes but loses access immediately.`))
      return;
    setBusy(user.id);
    try {
      await api.adminOffboardUser(user.id);
      await refresh();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  };

  const onSignOut = async () => {
    await signOut();
    router.replace("/sign-in");
  };

  const selectedTenant = useMemo(
    () => tenants?.find((t) => t.id === selected) ?? null,
    [tenants, selected],
  );

  return (
    <div className="flex min-h-screen flex-col bg-background text-text-primary">
      <GlobalHeader />

      <main className="mx-auto w-full max-w-7xl flex-1 px-6 py-8">
        <header className="flex flex-wrap items-end justify-between gap-3 border-b border-border pb-5">
          <div>
            <Link
              href="/admin"
              className="inline-flex items-center gap-1 font-mono text-[11px] uppercase tracking-wide text-text-muted hover:text-text-primary"
            >
              <ChevronLeft className="h-3 w-3" /> Back to admin
            </Link>
            <h1 className="mt-1 text-2xl font-semibold tracking-tight">User credentials</h1>
            <p className="mt-1 max-w-2xl text-sm text-text-secondary">
              Create users, reset passwords, change roles, and offboard. Plaintext
              passwords are echoed exactly once at creation / reset — copy them
              immediately, share via a secure channel.
            </p>
          </div>
          <div className="flex items-center gap-2">
            {scope ? (
              <span className="font-mono text-[10px] uppercase tracking-wide text-text-muted">
                Signed in as {scope.user_email} ({scope.role})
              </span>
            ) : null}
            <button
              onClick={() => void onSignOut()}
              className="inline-flex items-center gap-1.5 rounded-md border border-border bg-surface px-3 py-1.5 text-sm font-medium text-text-secondary transition-colors hover:text-text-danger"
            >
              <LogOut className="h-3.5 w-3.5" /> Sign out
            </button>
          </div>
        </header>

        {error ? (
          <div className="mt-5 rounded-md border border-danger bg-background p-3 text-sm text-text-danger">
            {error}
          </div>
        ) : null}

        <section className="mt-6 grid gap-4 lg:grid-cols-[280px_1fr]">
          <aside className="rounded-md border border-border bg-surface p-3">
            <h2 className="mb-3 px-1 font-mono text-[11px] uppercase tracking-wide text-text-muted">
              Tenants ({tenants?.length ?? "—"})
            </h2>
            {!tenants ? (
              <div className="px-1 text-xs text-text-secondary">Loading…</div>
            ) : tenants.length === 0 ? (
              <div className="px-1 text-xs text-text-secondary">No tenants yet.</div>
            ) : (
              <ul className="space-y-1">
                {tenants.map((t) => (
                  <li key={t.id}>
                    <button
                      onClick={() => setSelected(t.id)}
                      className={`w-full rounded-md px-2 py-2 text-left text-sm transition-colors ${
                        selected === t.id
                          ? "bg-navy text-white"
                          : "text-text-primary hover:bg-background-5"
                      }`}
                    >
                      <div className="font-medium">{t.name}</div>
                      <div
                        className={`font-mono text-[11px] ${
                          selected === t.id ? "text-white/70" : "text-text-muted"
                        }`}
                      >
                        {t.slug} · {t.status}
                      </div>
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </aside>

          <div className="space-y-4">
            <section className="rounded-md border border-border bg-surface p-5">
              <header className="flex flex-wrap items-end justify-between gap-3">
                <div>
                  <h2 className="font-mono text-[11px] uppercase tracking-wide text-text-muted">
                    Users in {selectedTenant?.name ?? "—"} ({users?.length ?? "—"})
                  </h2>
                  <p className="mt-0.5 text-xs text-text-secondary">
                    Owner has full access; admin can manage users and integrations;
                    member can use the assistant only.
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => void refresh()}
                    disabled={!selected || busy === "load"}
                    className="inline-flex items-center gap-1.5 rounded-md border border-border bg-background px-3 py-1.5 text-xs font-medium text-text-primary transition-colors hover:bg-background-5 disabled:opacity-50"
                  >
                    <RefreshCw
                      className={
                        "h-3.5 w-3.5 " + (busy === "load" ? "animate-spin" : "")
                      }
                    />
                    Refresh
                  </button>
                  <button
                    onClick={() => setShowCreate(true)}
                    disabled={!selected}
                    className="inline-flex items-center gap-1.5 rounded-md bg-navy px-3 py-1.5 text-sm font-medium text-white transition-colors hover:bg-navy-dark disabled:opacity-50"
                  >
                    <UserPlus className="h-3.5 w-3.5" /> Create user
                  </button>
                </div>
              </header>

              {!users ? (
                <p className="mt-3 text-xs text-text-secondary">Loading…</p>
              ) : users.length === 0 ? (
                <p className="mt-3 text-xs text-text-secondary">No users in this tenant yet.</p>
              ) : (
                <div className="mt-3 overflow-x-auto rounded-md border border-border">
                  <table className="w-full text-xs">
                    <thead className="bg-surface-blue text-text-secondary">
                      <tr className="text-left">
                        <th className="px-3 py-2">Email</th>
                        <th className="px-3 py-2">Name</th>
                        <th className="px-3 py-2">Role</th>
                        <th className="px-3 py-2">Status</th>
                        <th className="px-3 py-2">Last active</th>
                        <th className="px-3 py-2">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {users.map((u) => (
                        <tr key={u.id} className="border-t border-border-5 align-middle">
                          <td className="px-3 py-2 font-mono">{u.email}</td>
                          <td className="px-3 py-2">{u.name}</td>
                          <td className="px-3 py-2">
                            <select
                              value={u.role}
                              disabled={busy === u.id || u.id === scope?.user_id}
                              onChange={(e) =>
                                void onChangeRole(u, e.target.value as typeof ROLES[number])
                              }
                              className="rounded-sm border border-border bg-background px-2 py-1 font-mono text-[11px] uppercase tracking-wide text-text-primary outline-none transition-colors focus:border-navy disabled:opacity-50"
                            >
                              {ROLES.map((r) => (
                                <option key={r} value={r}>
                                  {r}
                                </option>
                              ))}
                            </select>
                          </td>
                          <td className="px-3 py-2">
                            <select
                              value={u.status}
                              disabled={busy === u.id || u.id === scope?.user_id}
                              title={
                                u.id === scope?.user_id
                                  ? "Cannot change your own status; ask another admin"
                                  : undefined
                              }
                              onChange={(e) =>
                                void onChangeStatus(
                                  u,
                                  e.target.value as typeof STATUSES[number],
                                )
                              }
                              className="rounded-sm border border-border bg-background px-2 py-1 font-mono text-[11px] uppercase tracking-wide text-text-primary outline-none transition-colors focus:border-navy disabled:opacity-50"
                            >
                              {STATUSES.map((s) => (
                                <option key={s} value={s}>
                                  {s}
                                </option>
                              ))}
                            </select>
                          </td>
                          <td className="px-3 py-2 font-mono text-text-muted">
                            {u.last_active_at ? u.last_active_at.slice(0, 19) : "—"}
                          </td>
                          <td className="px-3 py-2">
                            <div className="flex items-center gap-1.5">
                              <button
                                onClick={() => void onResetPassword(u)}
                                disabled={busy === u.id}
                                title="Generate new password and revoke sessions"
                                className="inline-flex items-center gap-1 rounded-sm border border-border px-2 py-0.5 font-mono text-[10px] uppercase tracking-wide text-text-secondary transition-colors hover:text-text-primary hover:bg-background-5 disabled:opacity-50"
                              >
                                <Key className="h-3 w-3" /> Reset pwd
                              </button>
                              <button
                                onClick={() => void onOffboard(u)}
                                disabled={busy === u.id || u.id === scope?.user_id}
                                title={
                                  u.id === scope?.user_id
                                    ? "Cannot offboard yourself"
                                    : "Soft-delete: status=offboarded, all sessions revoked"
                                }
                                className="inline-flex items-center gap-1 rounded-sm border border-border px-2 py-0.5 font-mono text-[10px] uppercase tracking-wide text-text-danger transition-colors hover:border-danger hover:bg-background-5 disabled:opacity-50"
                              >
                                <Trash2 className="h-3 w-3" /> Offboard
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </section>
          </div>
        </section>

        {showCreate && selected ? (
          <CreateUserModal
            tenantId={selected}
            tenantName={selectedTenant?.name ?? selected}
            onClose={() => setShowCreate(false)}
            onCreated={async (user, password, autoGenerated) => {
              setShowCreate(false);
              setReveal({ kind: "create", user, password, autoGenerated });
              await refresh();
            }}
          />
        ) : null}

        {reveal ? (
          <PasswordRevealModal reveal={reveal} onClose={() => setReveal(null)} />
        ) : null}
      </main>
      <GlobalFooter />
    </div>
  );
}

function CreateUserModal({
  tenantId,
  tenantName,
  onClose,
  onCreated,
}: {
  tenantId: string;
  tenantName: string;
  onClose: () => void;
  onCreated: (user: UserRow, password: string, autoGenerated: boolean) => Promise<void>;
}) {
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [role, setRole] = useState<typeof ROLES[number]>("member");
  const [autoGenerate, setAutoGenerate] = useState(true);
  const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const onSubmit = async (event: FormEvent) => {
    event.preventDefault();
    setErr(null);
    setBusy(true);
    try {
      const res = await api.adminCreateUser(tenantId, {
        email: email.trim(),
        name: name.trim(),
        role,
        password: autoGenerate ? undefined : password,
      });
      await onCreated(res.user, res.initial_password, res.auto_generated);
    } catch (e) {
      setErr((e as Error).message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"
      onClick={onClose}
    >
      <div
        className="w-full max-w-md rounded-md border border-border bg-surface-elevated p-6 shadow-md"
        onClick={(e) => e.stopPropagation()}
      >
        <header className="flex items-start justify-between gap-3">
          <div>
            <p className="font-mono text-[10px] uppercase tracking-wide text-text-muted">
              {tenantName}
            </p>
            <h2 className="mt-1 text-base font-semibold tracking-tight">Create user</h2>
            <p className="mt-1 text-xs text-text-secondary">
              The user receives no email automatically — you'll need to share
              the password with them out-of-band.
            </p>
          </div>
          <button
            onClick={onClose}
            className="rounded-sm p-1.5 text-text-secondary hover:bg-background-5 hover:text-text-primary"
          >
            <X className="h-4 w-4" />
          </button>
        </header>

        <form onSubmit={onSubmit} className="mt-5 space-y-4">
          <label className="block text-sm font-medium">
            Email
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              autoComplete="off"
              spellCheck={false}
              className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 font-mono text-xs text-text-primary outline-none transition-colors focus:border-navy"
            />
          </label>
          <label className="block text-sm font-medium">
            Display name
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
              autoComplete="off"
              className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-text-primary outline-none transition-colors focus:border-navy"
            />
          </label>
          <label className="block text-sm font-medium">
            Role
            <select
              value={role}
              onChange={(e) => setRole(e.target.value as typeof ROLES[number])}
              className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 font-mono text-xs uppercase tracking-wide text-text-primary outline-none transition-colors focus:border-navy"
            >
              {ROLES.map((r) => (
                <option key={r} value={r}>
                  {r}
                </option>
              ))}
            </select>
          </label>

          <fieldset className="space-y-2 rounded-md border border-border bg-background p-3">
            <legend className="px-1 font-mono text-[10px] uppercase tracking-wide text-text-muted">
              Initial password
            </legend>
            <label className="flex items-center gap-2 text-xs">
              <input
                type="radio"
                checked={autoGenerate}
                onChange={() => setAutoGenerate(true)}
              />
              <span>Auto-generate (16 chars, alphanumeric)</span>
            </label>
            <label className="flex items-center gap-2 text-xs">
              <input
                type="radio"
                checked={!autoGenerate}
                onChange={() => setAutoGenerate(false)}
              />
              <span>Set manually</span>
            </label>
            {!autoGenerate ? (
              <input
                type="text"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                minLength={8}
                required
                autoComplete="new-password"
                spellCheck={false}
                className="w-full rounded-md border border-border bg-background px-3 py-2 font-mono text-xs text-text-primary outline-none transition-colors focus:border-navy"
              />
            ) : null}
          </fieldset>

          {err ? (
            <div className="flex items-start gap-2 rounded-md border border-danger bg-background p-3 text-sm text-text-danger">
              <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
              <span>{err}</span>
            </div>
          ) : null}

          <div className="flex items-center justify-end gap-2">
            <button
              type="button"
              onClick={onClose}
              className="inline-flex items-center gap-1 rounded-md border border-border px-3 py-1.5 text-sm font-medium text-text-primary transition-colors hover:bg-background-5"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={busy}
              className="inline-flex items-center gap-1 rounded-md bg-navy px-3 py-1.5 text-sm font-medium text-white transition-colors hover:bg-navy-dark disabled:opacity-50"
            >
              <Plus className="h-3.5 w-3.5" />
              {busy ? "Creating…" : "Create user"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

function PasswordRevealModal({
  reveal,
  onClose,
}: {
  reveal: Reveal;
  onClose: () => void;
}) {
  const [copied, setCopied] = useState(false);
  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(reveal.password);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* ignore */
    }
  };
  const heading = reveal.kind === "create" ? "User created" : "Password reset";
  const subhead =
    reveal.kind === "create"
      ? `New password for ${reveal.user.email}`
      : `New password — all previous sessions revoked`;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"
      onClick={onClose}
    >
      <div
        className="w-full max-w-md rounded-md border border-success/40 bg-surface-elevated p-6 shadow-md"
        onClick={(e) => e.stopPropagation()}
      >
        <header className="flex items-start justify-between gap-3">
          <div>
            <p className="font-mono text-[10px] uppercase tracking-wide text-success">
              One-time reveal
            </p>
            <h2 className="mt-1 text-base font-semibold tracking-tight">{heading}</h2>
            <p className="mt-1 text-xs text-text-secondary">{subhead}</p>
          </div>
          <button
            onClick={onClose}
            className="rounded-sm p-1.5 text-text-secondary hover:bg-background-5 hover:text-text-primary"
          >
            <X className="h-4 w-4" />
          </button>
        </header>

        <div className="mt-5 rounded-md border border-border bg-background p-3">
          <p className="font-mono text-[10px] uppercase tracking-wide text-text-muted">
            {reveal.autoGenerated ? "Auto-generated password" : "Password"}
          </p>
          <p className="mt-1 break-all font-mono text-sm text-text-primary">
            {reveal.password}
          </p>
        </div>

        <div className="mt-3 flex items-center justify-between gap-2">
          <p className="text-[11px] text-text-muted">
            Copy now — this is the only time it's shown. It's hashed before it
            hits the database.
          </p>
          <button
            onClick={() => void onCopy()}
            className="inline-flex items-center gap-1 rounded-md border border-border bg-surface px-3 py-1.5 text-xs font-medium text-text-primary transition-colors hover:bg-background-5"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-success" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? "Copied" : "Copy"}
          </button>
        </div>

        <div className="mt-5 flex items-center justify-end">
          <button
            onClick={onClose}
            className="inline-flex items-center gap-1 rounded-md bg-navy px-3 py-1.5 text-sm font-medium text-white transition-colors hover:bg-navy-dark"
          >
            I've copied it — close
          </button>
        </div>
      </div>
    </div>
  );
}
