from enum import Enum


class ActivationState(str, Enum):
    """States from section 4.1 of TIGERI_AGENT_CATALOG_v1.md."""

    S0_SIGNED_IN = "S0_SIGNED_IN"
    S1_CRM_DISCOVERY = "S1_CRM_DISCOVERY"
    S2_MCP_CONNECT = "S2_MCP_CONNECT"
    S2_API_CONNECT = "S2_API_CONNECT"
    S3_CAPABILITY_INVENTORY = "S3_CAPABILITY_INVENTORY"
    S4_OBJECTIVE_INTAKE = "S4_OBJECTIVE_INTAKE"
    S5_AGENT_REASONING = "S5_AGENT_REASONING"
    S6_RECOMMENDATION_REVIEW = "S6_RECOMMENDATION_REVIEW"
    S7_AGENT_DEPLOY = "S7_AGENT_DEPLOY"
    S8_ACTIVE = "S8_ACTIVE"

    S_TERMINAL_ABORT = "S_TERMINAL_ABORT"
    S_FAIL_NO_CRM = "S_FAIL_NO_CRM"
    S_FAIL_INTEGRATION = "S_FAIL_INTEGRATION"
    S_FAIL_INTROSPECTION = "S_FAIL_INTROSPECTION"
    S_FAIL_NO_MATCH = "S_FAIL_NO_MATCH"
    S_FAIL_REJECT = "S_FAIL_REJECT"
    S_FAIL_DEPLOY = "S_FAIL_DEPLOY"


TERMINAL_STATES = {
    ActivationState.S8_ACTIVE,
    ActivationState.S_TERMINAL_ABORT,
    ActivationState.S_FAIL_NO_CRM,
    ActivationState.S_FAIL_INTEGRATION,
    ActivationState.S_FAIL_INTROSPECTION,
    ActivationState.S_FAIL_NO_MATCH,
    ActivationState.S_FAIL_DEPLOY,
}
